// ====== DOMANDE (catalogo) ======
const QUESTIONS_BANK = {
    'TORNIO MANUALE': {
      1: [
        { q: 'A cosa serve il tornio?', a:['Lavorare pezzi in rotazione','Saldare lastre','Misurare tolleranze'], correct:0 },
        { q: 'Prima dell’uso, verifica…', a:['Schermi e protezioni','Colore della leva','Rumore della sala'], correct:0 },
        { q: 'Il pezzo deve essere…', a:['Ben serrato nel mandrino','Appoggiato libero','Tenuto a mano'], correct:0 },
        { q: 'Trucioli lunghi vanno…', a:['Gestiti con ganci','Toccati a mani nude','Soffiati col fiato'], correct:0 },
        { q: 'DPI corretti?', a:['Occhiali, guanti idonei','Scarpe da mare','Cappello di lana'], correct:0 },
        { q: 'Interventi sul pezzo…', a:['A macchina ferma','A giri bassi','Durante la passata'], correct:0 },
        { q: 'Chiave mandrino…', a:['Mai lasciata inserita','Sempre inserita','Appesa al collo'], correct:0 },
        { q: 'Trucioli caldi…', a:['Non toccarli','Metterli in tasca','Bagnarli con acqua'], correct:0 },
        { q: 'Fine lavoro…', a:['Pulisci e isola macchina','Lascia trucioli','Aumenti i giri'], correct:0 },
        { q: 'Se senti vibrazioni…', a:['Fermati e controlla','Ignora','Aumenti avanzamento'], correct:0 },
      ],
      2: [
        { q:'Velocità di taglio dipende da…', a:['Materiale/utensile','Colore macchina','Ora del giorno'], correct:0 },
        { q:'La lunetta serve a…', a:['Sostenere pezzo lungo','Raffreddare','Misurare tensione'], correct:0 },
        { q:'Emulsione…', a:['Riduce calore/usura','Aumenta attrito','Colora trucioli'], correct:0 },
      ],
      3: [
        { q:'Filettatura al tornio…', a:['Sincronizza avanzamento e giri','Si fa a caso','Richiede trapano'], correct:0 },
      ],
    },
    'MOLATRICE': {
      1: [
        { q:'Prima di molare verifica…', a:['Integrità mola e flangie','Colore banco','Data sul cartello'], correct:0 },
        { q:'Schermi e occhiali…', a:['Obbligatori','Facoltativi','Sconsigliati'], correct:0 },
        { q:'La forza sul pezzo dev’essere…', a:['Moderata e costante','Massima','A colpi'], correct:0 },
      ],
    },
    'TRAPANO A COLONNA': {
      1: [
        { q:'Il pezzo va…', a:['Bloccato in morsa','Tenuto a mano','Appoggiato libero'], correct:0 },
        { q:'Trucioli si rimuovono…', a:['Con pennello/aria','Con le dita','Soffiando'], correct:0 },
        { q:'Prima di forare…', a:['Seleziona giri/avanzamento','Spegni luce','Alza tavola al massimo'], correct:0 },
      ],
    },
    'TRAPANO RADIALE': { 1: [ { q:'Braccio e colonna…', a:['Vanno serrati prima di forare','Si muovono durante il taglio','Non si serrano mai'], correct:0 } ] },
    'TRONCATRICE': { 1: [ { q:'Mai togliere protezioni…', a:['Corretto','Sbagliato','Indifferente'], correct:0 } ] },
    'CENTRO DI LAVORO': { 1: [ { q:'Cambio utensile automatico…', a:['Richiede zona libera','Si fa con pezzo in mano','Non ha rischi'], correct:0 } ] },
    'FRESATRICE': { 1: [ { q:'Frena/registra tavola…', a:['Per evitare vibrazioni','Per aumentare gioco','Per estetica'], correct:0 } ] },
    'CESOIA A GHIGLIOTTINA': { 1: [ { q:'Mani e scarti…', a:['Lontani dalla lama','Vicini per guida','Spingere con dita'], correct:0 } ] },
    'PRESSA PIEGATRICE': { 1: [ { q:'Barriere fotoelettriche…', a:['Non si bypassano','Si coprono','Si staccano'], correct:0 } ] },
    'SEGA A NASTRO': { 1: [ { q:'Guidalama…', a:['Regolato vicino al pezzo','Sempre alto','Inutile'], correct:0 } ] },

    'CARRELLO ELEVATORE': {
      1: [
        { q:'Cintura e uomo a terra…', a:['Cintura allacciata, no passeggeri','Due a bordo','Si guida in piedi'], correct:0 },
        { q:'Portata nominale…', a:['Da rispettare','Indicativa','Si raddoppia con contrappesi'], correct:0 },
        { q:'Carico in quota…', a:['Basso e inclinazione minima','Alto per visibilità','Inclinato in avanti'], correct:0 },
      ],
      2: [
        { q:'Stabilità dipende da…', a:['Triangolo di stabilità','Colore forche','Marca'], correct:0 },
      ],
      3: [
        { q:'Soste su pendenze…', a:['Evitarle / mettere freno','Indifferenti','Motore spento e folle'], correct:0 },
      ],
    },
    'TRABATTELLO O PONTE A TORRE': {
      1: [
        { q:'Ruote…', a:['Con freno e stabilizzatori','Sempre senza freno','Con freno solo in salita'], correct:0 },
        { q:'Parapetti…', a:['Completi ai piani','Solo lato esterno','Inutili sotto i 2 m'], correct:0 },
      ],
    },
    'SCALE PORTATILI': {
      1: [
        { q:'Inclinazione corretta…', a:['Circa 75° (1:4)','90° verticale','45°'], correct:0 },
        { q:'Piano di appoggio…', a:['Solido e antisdrucciolo','Qualsiasi','Gradino instabile'], correct:0 },
      ],
    },
    'PARANCHI': {
      1: [
        { q: 'A cosa serve il paranco?', a:['Sollevare e movimentare carichi','Fissare strutture','Misurare lunghezze'], correct:0 },
        { q: 'Qual è il controllo principale prima dell\'uso?', a:['Verificare portata e ganci','Controllare il colore','Lubrificare a caso'], correct:0 },
        { q: 'Durante il sollevamento, il carico deve essere…', a:['Ben imbragato e bilanciato','Inclinato di 30°','Appoggiato al suolo'], correct:0 },
        { q: 'Il comando deve essere…', a:['In vista del carico','Sempre dietro il carico','Lontano 50 m'], correct:0 },
        { q: 'Cosa NON si deve fare?', a:['Sostare sotto carichi sospesi','Usare segnali convenzionali','Verificare interferenze'], correct:0 },
        { q: 'Il gancio con linguetta serve a…', a:['Evitare lo sgancio accidentale','Ridurre il rumore','Aumentare la portata'], correct:0 },
        { q: 'Portata nominale significa…', a:['Massa massima sollevabile','Altezza massima','Velocità catena'], correct:0 },
        { q: 'Imbracature danneggiate…', a:['Vanno scartate','Si riparano con nastro','Si usano solo di giorno'], correct:0 },
        { q: 'In caso di anomalia durante il sollevamento…', a:['Fermare e mettere in sicurezza','Accelerare','Ignorare e proseguire'], correct:0 },
        { q: 'Per comunicare con l\'operatore gru…', a:['Usare segnali e/o radio','Urla e fischi','Luci intermittenti'], correct:0 },
      ],
    },
    'IMBRAGO DEI CARICHI': {
      1: [
        { q:'Angolo di imbracatura…', a:['Ridurlo per aumentare portata','Non conta','Sempre >120°'], correct:0 },
        { q:'Nodi su brache…', a:['Vietati','Consigliati','Indifferenti'], correct:0 },
      ],
    },
    'PLE': { 1: [ { q:'Imbracatura in cesta…', a:['Obbligatoria','Facoltativa','Sconsigliata'], correct:0 } ] },
    'PONTEGGI': { 1: [ { q:'Accessi e parapetti…', a:['Devono essere completi','Solo lato esterno','Opzionali'], correct:0 } ] },

    'DISPOSITIVI DI PROTEZIONE': {
      1: [
        { q:'DPI testa…', a:['Elmetto conforme e integro','Cappellino da baseball','Cuffia in lana'], correct:0 },
        { q:'Guanti…', a:['Adeguati al rischio','Sempre uguali','Mai necessari'], correct:0 },
      ],
      2: [
        { q:'Occhiali/visiere…', a:['Contro proiezioni','Solo per estetica','Non servono'], correct:0 },
      ],
      3: [
        { q:'Udito…', a:['Inserto o cuffie idonee','Cotone','Tappi improvvisati'], correct:0 },
      ],
      4: [
        { q:'Vie respiratorie…', a:['Filtro idoneo al contaminante','Mascherina generica','Panno'], correct:0 },
      ],
      5: [
        { q:'Calzature…', a:['Puntale/lamina se richiesto','Sandali','Scarpe eleganti'], correct:0 },
      ],
    },
    'IMBRAGATURA': {
      1: [
        { q:'Controlli pre-uso…', a:['Cuciture, fibbie, etichette','Colore bretelle','Logo'], correct:0 },
        { q:'Punto di ancoraggio…', a:['Idoneo e certificato','Maniglia porta','Tubo di rame'], correct:0 },
      ],
    },
    'DPI E SEGNALETICA': {
      1: [
        { q:'Cartelli obbligo…', a:['Indicano DPI da indossare','Decorazioni','Pubblicità'], correct:0 },
        { q:'Divieto “vietato fumare”…', a:['Rischio incendio/ambiente','Solo cortesia','Opzionale'], correct:0 },
      ],
      2: [
        { q:'Segnaletica di emergenza…', a:['Uscite e presidi antincendio','Area relax','Zona fumatori'], correct:0 },
      ],
      3: [
        { q:'Colore giallo/nero…', a:['Attenzione/pericolo','Vietato','Obbligo'], correct:0 },
      ],
    },
    'RISCHIO INCENDIO': {
      1: [
        { q:'Qual è l’elemento necessario perché un incendio possa iniziare?', a:['Solo l’ossigeno','Un innesco (fonte di calore)','Solo il combustibile'], correct:1 },
        { q:'Cosa rappresenta il “triangolo del fuoco”?', a:['Tre tipi di estintori','Combustibile + comburente + fonte di calore','Tre classi di incendio'], correct:1 },
		{ q:'Quale tra questi è un esempio di possibile causa di innesco?', a:['Una lampada accesa','Una scintilla elettrica','Una finestra aperta'], correct:1 },
        { q:'Quale materiale può agire come combustibile in un incendio?', a:['Solo i liquidi','Carta, legno, tessuti, plastica','Solo i metalli'], correct:1 },
        { q:'La propagazione dell’incendio può avvenire attraverso:', a:['Solo per contatto diretto','Conduzione, convezione e irraggiamento','Solo tramite l’aria calda'], correct:1 },
        { q:'Una causa comune di incendio negli ambienti di lavoro è:', a:['Luci led','Il surriscaldamento di impianti elettrici','Ambienti caldi'], correct:1 },
        { q:'Perché la presenza di materiali infiammabili aumenta il rischio incendio?', a:['Perché occupano spazio','Perché fanno aumentare la temperatura','Perché alimentano la combustione facilitando la propagazione'], correct:2 },
        { q:'Gli incendi possono generare fumi tossici che:', a:['Sono innocui se si esce velocemente','Possono compromettere la respirazione e causare perdita di orientamento','Servono a spegnere il fuoco'], correct:1 },
        { q:'Qual è una delle principali conseguenze di un incendio sul luogo di lavoro?', a:['La riduzione del consumo elettrico','Danni a persone, strutture e interruzione dell’attività','Maggior ventilazione dei locali'], correct:1 },
        { q:'Per ridurre il rischio incendio è importante:', a:['Accumulare materiali per ottimizzare lo spazio','Mantenere ordine e corretto stoccaggio dei materiali','Tenere le porte sempre aperte'], correct:1 },
	  ],
      2: [
        { q:'Quale condizione favorisce maggiormente l’innesco di un incendio in un impianto elettrico?', a:['Impianto nuovo','Sovraccarico o cattiva manutenzione','Presenza di prese multiple'], correct:1 },
		{ q:'Quale tra questi è un esempio di combustione lenta che può diventare incendio?', a:['Un mozzicone acceso gettato su materiale secco ','Legno umido che non brucia','Una lampadina a LED'], correct:0 },
		{ q:'Perché gli ambienti poco ventilati aumentano il rischio incendio?', a:['Perché non permettono la propagazione del calore','Perché ostacolano la combustione','Perché favoriscono l’accumulo di fumi e calore '], correct:2 },
		{ q:'La propagazione verticale dell’incendio avviene soprattutto tramite:', a:['Conduzione nei pavimenti','Movimento dei gas caldi verso l’alto (convezione) ','Umidità dell’ambiente'], correct:1 },
		{ q:'Perché la presenza di liquidi infiammabili aumenta la velocità di propagazione?', a:['Perché evaporano facilmente creando atmosfere esplosive ','Perché sono più pesanti dell’aria','Perché raffreddano il fuoco'], correct:0 },
		{ q:'Le polveri combustibili (farine, segatura, polveri metalliche):', a:['Possono esplodere se disperse nell’aria in concentrazioni adeguate ','Non bruciano mai ','Sono pericolose solo se bagnate'], correct:0 },
		{ q:'La mancanza di ordine e pulizia in un ambiente di lavoro può:', a:['Ridurre la probabilità di incendio','Non avere alcun impatto','Ostacolare le vie di fuga e aumentare il rischio di propagazione '], correct:2 },
		{ q:'Quale segnale indica un potenziale surriscaldamento elettrico?', a:['Rumore di vento','Odore di bruciato o prese molto calde','Luci troppo luminose'], correct:1 },
		{ q:'Perché l’accumulo di rifiuti combustibili rappresenta un pericolo?', a:['Perché rende l’ambiente disordinato','Perché può fungere da combustibile e generare incendi secondari ','Perché attira insetti'], correct:1 },
		{ q:'Cosa può determinare una “flashover” (fiammata generalizzata)?', a:['Un calo improvviso di ossigeno','Il raffreddamento dei gas','L’aumento estremo della temperatura dei fumi che prende fuoco simultaneamente'], correct:2 },
      ],
	  3: [
        { q:'Qual è un comportamento ERRATO molto comune in caso di fumo in un locale?', a:['Restare bassi e cercare l’uscita','Camminare in piedi respirando aria calda e fumo','Coprire naso e bocca con un panno'], correct:1 },
		{ q:'Qual è un comportamento scorretto durante una evacuazione?', a:['Seguire la segnaletica di emergenza','Mantenere la calma','Correre e spingere per uscire più in fretta'], correct:2 },
		{ q:'Nel caso di incendi che coinvolgono oli e grassi da cucina, perché l’acqua non deve essere usata?', a:['Perché può raffreddare troppo l’olio','Perché diluisce l’olio','Perché provoca un’espulsione violenta dell’olio e un aumento delle fiamme'], correct:2 },
		{ q:'Cosa può determinare la rapida propagazione dell’incendio in un capannone con scaffalature alte?', a:['La scarsa umidità','L’effetto camino creato dal calore che sale tra le scaffalature','La presenza di luci artificiali'], correct:1 },
		{ q:'Perché la presenza di ossigeno concentrato (bombole, medicale, industriale) è un fattore di rischio incendio?', a:['Perché l’ossigeno è combustibile','Perché rallenta la combustione','Perché accelera notevolmente la combustione e aumenta la violenza delle fiamme'], correct:2 },
		{ q:'Cosa NON deve fare un lavoratore quando vede un principio d’incendio?', a:['Dare l’allarme','Allontanarsi in sicurezza','Tentare di spegnere il fuoco senza essere addestrato o avere una via di fuga'], correct:2  },
		{ q:'Perché un incendio in un locale chiuso può diventare improvvisamente incontrollabile?', a:['Bassa umidità e assenza totale di aria','Elevata concentrazione delle polveri in sospensione + innesco','Grani troppo grossi di materiale combustibile'], correct:1 },
		{ q:'Qual è un comportamento errato rispetto agli estintori?', a:['Usare l’estintore indirizzando il getto alla base delle fiamme','Controllare che sia quello giusto per la classe di incendio','Rimuovere i sigilli per “provarlo”'], correct:2 },
		{ q:'Cosa NON deve fare un lavoratore se la porta di un locale è calda?', a:['Cercare un’altra via di fuga','Avvisare il responsabile dell’emergenza','Aprire la porta comunque per “controllare meglio”'], correct:2 },
		{ q:'Perché il fumo è considerato spesso più pericoloso del fuoco?', a:['Perché ostacola la visibilità, contiene sostanze tossiche e può causare perdita di coscienza in pochi minuti','Perché è dannoso','Perché ha un odore forte'], correct:0 },
      ],
	  4: [
        { q:'Perché una sigaretta può causare un incendio anche quando sembra spenta?', a:['Perché continua a generare una brace molto calda capace di incendiare materiali secchi','Perché aumenta la temperatura dell’aria','Perché produce molto fumo'], correct:0 },
		{ q:'Qual è un comportamento assolutamente vietato nelle aree di lavoro non designate al fumo?', a:['Parlare con i colleghi','Accendere una sigaretta vicino a materiali infiammabili (carta, solventi, legno, rifiuti)','Bere acqua'], correct:1 },
		{ q:'Dove è assolutamente vietato fumare per rischio di innesco?', a:['In zone designate al fumo','All’aperto lontano da materiali','Vicino a liquidi infiammabili o bombole'], correct:2 },
		{ q:'Perché i mozziconi non devono essere gettati nei cestini dei rifiuti normali?', a:['Perché fanno cattivo odore','Perché occupano spazio','Perché possono incendiare carta o materiali presenti nel cestino, propagando un incendio'], correct:2 },
		{ q:'Qual è un comportamento ERRATO molto comune in caso di fumo in un locale?', a:['Restare bassi e cercare l’uscita','Camminare in piedi respirando aria calda e fumo','Coprire naso e bocca con un panno'], correct:1 },
		{ q:'Qual è il contenitore corretto per smaltire i mozziconi nelle aree fumatori?', a:['Sacchetto di plastica','Cestino per la carta','Posacenere ignifugo o contenitore metallico chiuso'], correct:2 },
		{ q:'Quale cartello deve essere presente in un’area dove è vietato fumare?', a:['Cartello “Obbligo di spegnere le luci”','Cartello “Divieto di fumare” con simbolo standard ','Cartello “Attenzione pavimento bagnato”'], correct:1 },
		{ q:'Cos’è un "innesco lento" dovuto a sigarette?', a:['Un incendio che parte immediatamente','Una combustione interna che può trasformarsi in incendio ore dopo, ad esempio in un cestino','Un fuoco che non aumenta mai'], correct:1 },
		{ q:'Qual è un comportamento corretto in azienda per gestire il fumo?', a:['Creare zone fumatori esterne, sicure e lontane da materiali combustibili','Permettere di fumare vicino alle uscite','Permettere di fumare in magazzino se ventilato'], correct:0 },
		{ q:'Cosa deve fare un lavoratore che nota un mozzicone ancora acceso in un’area non fumatori?', a:['Ignorarlo se non ci sono supervisori','Segnalare il rischio e spegnerlo in sicurezza, se possibile','Lasciarlo raffreddare da solo'], correct:1 },
      ],
    },
	'ESTINTORI': {
      1: [
        { q:'Quale colore identifica generalmente un estintore portatile?', a:['Blu','Rosso','Verde'], correct:1 },
        { q:'L’estintore a polvere è particolarmente efficace su quali tipi di incendio?', a:['Solo incendi elettrici','Solo incendi di liquidi','Incendi di classe A, B e C (multiclasse)'], correct:2 },
		{ q:'L’estintore a CO₂ è principalmente utilizzato per:', a:['Incendi di carta e legno','Incendi elettrici e di liquidi infiammabili','Incendi di metalli'], correct:1 },
        { q:'L’estintore ad acqua è indicato per incendi di:', a:['Materiali solidi combustibili (legno, carta, tessuti)','Liquidi infiammabili','Apparecchiature elettriche'], correct:0 },
        { q:'Quale estintore NON deve essere usato su impianti elettrici sotto tensione?', a:['CO₂','Polvere','Acqua a getto pieno '], correct:2 },
        { q:'Qual è il primo passo per utilizzare un estintore?', a:['Puntarlo verso il soffitto','Togliere la spina di sicurezza (o linguetta)','Sdraiarsi a terra'], correct:1 },
        { q:'L’estintore a schiuma è particolarmente indicato per:', a:['Incendi di liquidi infiammabili (classe B)','Incendi di metalli','Incendi elettrici'], correct:0 },
        { q:'Cosa indica la sigla “CO₂” sugli estintori?', a:['Monossido di carbonio','Anidride carbonica (carbon dioxide)','Ossigeno liquido'], correct:1 },
        { q:'Dove è preferibile utilizzare un estintore a CO₂?', a:['Locali chiusi con apparecchiature elettriche, per evitare residui di polvere','All’aperto','Su materiali solidi in combustione'], correct:0 },
        { q:'Come deve essere indirizzato il getto dell’estintore su un incendio?', a:['Direttamente alla base delle fiamme','Verso la parte più alta della fiamma','In aria sopra l’incendio'], correct:0 },
	  ],
      2: [
        { q:'Quale classe di incendio è rappresentata da liquidi infiammabili come benzina o solventi?', a:['Classe A','Classe B','Classe F'], correct:1 },
		{ q:'Un estintore a polvere può essere utilizzato su quadri elettrici fino a quale tensione massima (indicativa) prima che si ritenga inadatto?', a:['Fino a 3000 V','Fino a 1000 V','Fino a 500 V'], correct:1 },
		{ q:'Quale caratteristica rende l’estintore a CO₂ inadatto a spazi molto piccoli e senza ventilazione?', a:['Produce residui tossici','Riduce l’ossigeno nell’ambiente, rischiando asfissia','È troppo pesante'], correct:1 },
		{ q:'Per incendi di oli e grassi da cucina (classe F), qual è l’estintore corretto?', a:['Estintore a polvere','Estintore a CO₂','Estintore a base di soluzione chimica (wet chemical)'], correct:2 },
		{ q:'Per la collocazione degli estintori, il percorso massimo che un operatore deve percorrere per raggiungerlo è:', a:['15 metri','10 metri','25 metri'], correct:0 },
		{ q:'La pressione di un estintore portatile si verifica tramite:', a:['Agitare l’estintore','Controllare il manometro, se presente, nella zona verde ','Aprire la valvola di sicurezza'], correct:1 },
		{ q:'Quale estintore è più efficace su incendi di gas (classe C)?', a:['Estintore a polvere ABC o BC ','Estintore a schiuma','Estintore ad acqua'], correct:0 },
		{ q:'Prima di azionare un estintore è consigliabile:', a:['Chiamare immediatamente i vigili del fuoco (115) e individuare una via di fuga ','Posizionarsi vicino al fuoco e poi togliere la spina di sicurezza','Agire subito senza considerare l’ambiente circostante'], correct:0 },
		{ q:'Quale pericolo si può avere usando un estintore a CO₂ in ambienti molto freddi?', a:['Il gas potrebbe incendiarsi','L’ugello può congelare e causare ustioni da freddo al contatto con la pelle ','L’estintore esplode facilmente'], correct:1 },
		{ q:'Si raccomanda che, durante l’uso di un estintore, l’operatore si posizioni ad una distanza massima di circa?', a:['4 metri dal fuoco ','1 metro dal fuoco ','10 metri dal fuoco '], correct:0 },
      ],
	  3: [
        { q:'Qual è il primo gesto tecnico da compiere per utilizzare correttamente un estintore?', a:['Impugnare il tubo e dirigersi verso il fuoco','Togliere la spina di sicurezza (o linguetta)','Premere subito la leva di erogazione'], correct:1 },
		{ q:'Durante l’uso dell’estintore, il tubo di scarica deve essere mantenuto:', a:['In posizione verticale verso l’alto','Leggermente inclinato verso il pavimento','In direzione orizzontale verso la base delle fiamme '], correct:2 },
		{ q:'Quanti addetti al primo soccorso devono essere presenti sul luogo di lavoro?', a:['Un numero fisso stabilito dalla legge per ogni azienda','Almeno un addetto presente in ogni momento, tenendo conto di turni, ferie e assenze','Solo uno per azienda, indipendentemente dagli orari'], correct:1 },
		{ q:'Perché l’estintore a CO₂ non è efficace sugli incendi di materiali solidi (classe A)?', a:['Perché il gas non può penetrare nel materiale e raffreddarlo, permettendo la ripresa dell’incendio','Perché scade più rapidamente','Perché il gas è infiammabile'], correct:0 },
		{ q:'Quale parametro influenza maggiormente la distanza di utilizzo di un estintore?', a:['La temperatura dell ambiente','La pressione interna e il tipo di agente estinguente (polvere, CO₂, schiuma)','Il colore dell’estintore'], correct:1 },
		{ q:'Per un lavoratore che opera da solo (lavoratore isolato), cosa deve prevedere il datore di lavoro secondo le indicazioni riportate?', a:['Una valutazione specifica del rischio e strumenti di comunicazione idonei per chiedere soccorso in caso di emergenza','Nessuna misura aggiuntiva rispetto agli altri lavoratori','La presenza costante di un addetto antincendio accanto a lui'], correct:0  },
		{ q:'Quale procedura è corretta quando si utilizza un estintore a polvere in un locale chiuso con scarsa visibilità?', a:['Spegnere le luci e dirigersi verso le fiamme','Usarlo con cautela perché la nube di polvere riduce ulteriormente la visibilità, rischiando disorientamento','Erogare tutta la carica subito senza pause'], correct:1 },
		{ q:'Quali sono i componenti essenziali di un estintore?', a:['Valvola, carrello, agenti estinguenti','Serbatoio, valvola, agenti estinguenti, manichetta, propellente','Solo serbatoio, manichetta e agente estinguente'], correct:1 },
		{ q:'Quale è la distinzione tra estintori portatili e carrellati?', a:['Gli estintori portatili sono fissati al muro, gli estintori carrellati sono trasportabili su carrello','Portatili = carica ≤ 20 kg e uso da parte di un solo operatore; Carrellati = carica > 20 kg, su ruote e uso da due operatori','Portatili = solo CO₂; Carrellati = solo polvere'], correct:1 },
		{ q:'Quale agente estinguente, tra quelli descritti, lascia residui che possono danneggiare macchinari e componenti sensibili?', a:['Polvere estinguente','CO₂','Acqua nebulizzata'], correct:0 },
      ],
    },
	'PROCEDURE DI SICUREZZA': {
      1: [
        { q:'Qual è la prima cosa da fare quando si scopre un incendio?', a:['Cercare di spegnerlo da soli','Dare immediatamente l’allarme','Spegnere le luci'], correct:1 },
        { q:'Qual è il numero unico dei Vigili del Fuoco in Italia?', a:['118','113','115'], correct:2 },
		{ q:'Cosa bisogna fare se la stanza è piena di fumo?', a:['Camminare normalmente','Restare bassi e coprire bocca e naso ','Aprire tutte le finestre'], correct:1 },
        { q:'Se l’incendio è piccolo e gestibile, quale azione è corretta?', a:['Usare l’estintore se si è addestrati ','Lanciarci sopra dell’acqua senza valutare il rischio','Correre verso il fuoco per spegnerlo'], correct:0 },
        { q:'Cosa NON bisogna fare durante un incendio?', a:['Mantenere la calma','Usare l’ascensore','Avvisare gli altri'], correct:1 },
        { q:'L’evacuazione deve avvenire seguendo:', a:['Il percorso più vicino anche se non segnato','Solo il proprio istinto','Le vie di esodo indicate dalla segnaletica di emergenza'], correct:2 },
        { q:'Se la porta di una stanza è calda al tatto, cosa bisogna fare?', a:['Aprirla lentamente','Aprirla velocemente','Non aprirla, perché potrebbe esserci fuoco dall’altra parte '], correct:1 },
        { q:'Quando ci si mette in salvo all’esterno, occorre:', a:['Rientrare per recuperare oggetti personali','Rimanere nel punto di raccolta fino all’appello','Allontanarsi e andare a casa'], correct:1 },
        { q:'Chi può decidere di interrompere l’evacuazione o autorizzare il rientro?', a:['Ogni singolo lavoratore','Il coordinatore dell’emergenza o i Vigili del Fuoco','Chi è già uscito per primo'], correct:1 },
        { q:'Se si usa un estintore, dove va direzionato il getto?', a:['Alla base delle fiamme','Verso il soffitto','A caso per creare una nube'], correct:0 },
	  ],
      2: [
        { q:'Prima di tentare di spegnere un principio d’incendio, cosa deve valutare l’operatore?', a:['Se l’estintore è del colore preferito','Se il fuoco è controllabile e se ha una via di fuga sicura','Se ci sono spettatori'], correct:1 },
		{ q:'Qual è la priorità assoluta nella gestione di un’emergenza incendio?', a:['Salvare i macchinari','Mettere in sicurezza le persone','Chiudere l’impianto elettrico'], correct:1 },
		{ q:'In caso di incendio, quando è opportuno chiudere porte e finestre?', a:['Quando si è certi di potersene andare subito dopo','Sempre, per limitare l’ingresso di ossigeno e la propagazione del fumo','Mai, perché ostacolano l’uscita'], correct:1 },
		{ q:'Qual è il comportamento corretto se l’allarme antincendio suona?', a:['Continuare il lavoro finché non arriva conferma','Interrompere le attività e avviarsi verso le uscite di emergenza', 'Spegnere l’allarme da soli'], correct:1 },
		{ q:'Perché si deve evitare di aprire una porta se dietro c’è fumo o calore?', a:['Per non consumare energia','Perché l’apertura può alimentare il fuoco con ossigeno causando una fiammata','Per non disturbare i colleghi'], correct:1 },
		{ q:'In caso di forte fumo, qual è il modo più sicuro di spostarsi?', a:['Correre velocemente','Restare bassi e procedere lentamente a terra','Respirare profondamente'], correct:1 },
		{ q:'Se un collega manca all’appello nel punto di raccolta, chi può tornare dentro a cercarlo?', a:['Un volontario tra i lavoratori','L’addetto antincendio solo se lo ritiene opportuno','Nessuno: devono intervenire solo i soccorritori qualificati (Vigili del Fuoco) '], correct:2 },
		{ q:'Perché è importante lasciare libere le vie di esodo?', a:['Per facilitare la pulizia','Per consentire un’evacuazione rapida e sicura e l’accesso dei soccorritori','Per ragioni estetiche'], correct:1 },
		{ q:'Qual è l’azione corretta da compiere prima di usare un idrante antincendio a muro?', a:['Verificare che la manichetta sia integra e completamente srotolata','Riempire la manichetta d’acqua manualmente','Tenere l’idrante chiuso per evitare rumore'], correct:0 },
		{ q:'In un’evacuazione, perché è vietato spingere o correre?', a:['Per evitare sudorazione','Per evitare panico e cadute che ostacolerebbero la fuga','Per mantenere il silenzio'], correct:1 },
      ],
	  3: [
        { q:'In un incendio all’interno di un edificio industriale, chi ha l’autorità di dichiarare conclusa l’emergenza?', a:['Il responsabile di reparto','Il primo lavoratore che esce','Il Coordinatore dell’Emergenza o i Vigili del Fuoco'], correct:2 },
		{ q:'In caso di incendio in un quadro elettrico, qual è la prima azione corretta?', a:['Lanciare acqua per raffreddare','Disattivare la corrente se possibile, senza esporsi a rischi','Aprire il quadro per controllare meglio'], correct:1 },
		{ q:'Perché è fondamentale chiudere porte REI durante un incendio?', a:['Per diminuire il rumore','Per rallentare la propagazione di fumo e calore tra compartimenti','Per non far entrare aria fredda'], correct:1 },
		{ q:'Durante un’evacuazione, quando è possibile cambiare percorso rispetto a quello previsto dal piano di emergenza?', a:['Mai, anche se il percorso è bloccato', 'Solo se il percorso previsto è pericoloso o inaccessibile e ci sono vie alternative sicure', 'Quando si vuole fare più in fretta'], correct:1 },
		{ q:'Qual è la prima responsabilità dell’addetto antincendio quando riceve una segnalazione di fumo o fuoco?', a:['Cercare l’origine del fumo da solo','Verificare la situazione senza esporsi a pericoli e confermare l’allarme','Spegnere subito qualsiasi principio di fuoco'], correct:1 },
		{ q:'Quando può intervenire direttamente sul fuoco un addetto antincendio?', a:['Sempre, per dimostrare prontezza','Solo se il fuoco è di piccole dimensioni e l’addetto ha una via di fuga sicura','Solo se è presente almeno un altro addetto'], correct:1  },
		{ q:'Cosa deve fare un addetto antincendio se, durante un tentativo di spegnimento, perde la visibilità a causa del fumo?', a:['Continuare comunque','Ritirarsi immediatamente seguendo il percorso di fuga','Restare fermo finché il fumo non si dirada'], correct:1 },
		{ q:'Qual è la condizione essenziale per usare in sicurezza un estintore CO₂ in un ambiente chiuso?', a:['Avere un estintore molto grande','Garantire ventilazione adeguata per evitare rischio di asfissia','Spegnere tutte le luci'], correct:1 },
		{ q:'Se un estintore non funziona durante l’intervento, l’addetto deve:', a:['Continuare a premere la leva finché parte','Abbandonare l’estintore, ritirarsi e segnalarlo come fuori uso', 'Smontarlo sul posto'], correct:1 },
		{ q:'L’addetto antincendio ha l’obbligo di:', a:['Prendere iniziative personali non previste','Seguire rigidamente il piano di emergenza e comunicare ogni anomalia al coordinatore','Disattivare sistemi tecnici anche senza formazione'], correct:1 },
      ],
    },
	'DPI E SEGNALETICA': {
      1: [
        { q:'Cosa sono i DPI antincendio?', a:['Dispositivi utilizzati dai vigili urbani','Dispositivi di Protezione Individuale specifici per l’emergenza incendio','Documenti Preventivi di Intervento'], correct:1 },
        { q:'Quale tra questi è un DPI antincendio di base?', a:['Casco con visiera resistente al calore','Cappello di lana','Tuta ad alta visibilità'], correct:0 },
		{ q:'Che tipo di guanti usa un addetto antincendio?', a:['Guanti in cotone leggero','Guanti isolanti e resistenti al calore ','Guanti da giardinaggio'], correct:1 },
        { q:'Qual è lo scopo principale della maschera filtrante antincendio?', a:['Proteggere dal rumore','Proteggere da fumi e gas tossici durante un incendio','Migliorare la vista'], correct:1 },
        { q:'La segnaletica antincendio è di colore:', a:['Verde','Giallo','Rosso'], correct:2 },
        { q:'Un cartello con il simbolo dell’estintore indica:', a:['Uscita di emergenza','Presenza dell’estintore ','Divieto di fumare'], correct:1 },
        { q:'Quale DPI è usato per proteggere il volto da calore e fiamme?', a:['Cappuccio ignifugo e visiera protettiva ','Occhiali da sole','Mascherina chirurgica'], correct:0 },
        { q:'I cartelli antincendio servono a:', a:['Indicare comportamenti vietati','Segnalare attrezzature utili contro l’incendio (idranti, estintori, allarmi)','Segnalare materiali pericolosi'], correct:1 },
        { q:'Quale degli indumenti seguenti può far parte dell’equipaggiamento antincendio leggero?', a:['Maglietta in cotone','Giacca ignifuga resistente al calore ','Impermeabile da pioggia'], correct:1 },
        { q:'La segnaletica antincendio ha in genere forma:', a:['Triangolare','Circolare','Quadrata o rettangolare'], correct:2 },
	  ],
      2: [
        { q:'Qual è lo scopo principale della segnaletica antincendio secondo la normativa?', a:['Informare sulla presenza di procedure aziendali','Segnalare attrezzature e dispositivi utili in caso di incendio','Indicare i percorsi di evacuazione'], correct:1 },
		{ q:'Il colore ROSSO nella segnaletica antincendio indica:', a:['Attrezzature di emergenza antincendio','Avvertenze generiche','Materiali pericolosi'], correct:0 },
		{ q:'Qual è la forma standard dei cartelli antincendio secondo la normativa UNI EN ISO 7010?', a:['Cerchio','Quadrato o rettangolo con pittogramma bianco su fondo rosso','Triangolo rosso'], correct:1 },
		{ q:'Cosa indica il cartello verde con la tre persone e quattro frecce che puntano verso il centro?', a:['Punto di raccolta ','Presenza di idrante antincendio', 'Uscita di emergenza'], correct:0 },
		{ q:'Quale cartello segnala la posizione del pulsante di allarme incendio?', a:['Sirena stilizzata su sfondo rosso','Fiamma gialla in triangolo','Estintore in cerchio blu'], correct:0 },
		{ q:'Dove devono essere posizionati i cartelli antincendio?', a:['Dove preferisce il lavoratore','In zone nascoste per non disturbare','In luighi ben visibili, ad altezza adeguata e non coperti da ostacoli'], correct:2 },
		{ q:'Quale funzione ha il cartello “Lancia antincendio”?', a:['Segnala la presenza di un estintore','Indica dove si trova il sistema di spegnimento con manichetta/idrante a muro','Indica l’attrezzatura per lavori in quota'], correct:1 },
		{ q:'La segnaletica antincendio deve essere conforme a quale standard europeo?', a:['UNI EN ISO 7010 ','UNI EN 2040','ISO 9001'], correct:0 },
		{ q:'Quale caratteristica NON deve avere un cartello antincendio?', a:['Buona leggibilità anche da lontano','Colori stabili e resistenti nel tempo','Essere mimetico con l’ambiente'], correct:2 },
		{ q:'A cosa serve la freccia rossa sui cartelli antincendio?', a:['Indica la direzione del vento','Indica la direzione per raggiungere l’attrezzatura antincendio','Indica il punto di ritrovo'], correct:1 },
      ],
	  3: [
        { q:'Qual è lo scopo principale della segnaletica antincendio secondo la normativa?', a:['Informare sulla presenza di procedure aziendali','Segnalare attrezzature e dispositivi utili in caso di incendio','Indicare i percorsi di evacuazione'], correct:1 },
		{ q:'Qual è il criterio principale per scegliere tra cartello adesivo, rigido o fotoluminescente?', a:['Preferenza del datore di lavoro','Tipo di supporto e condizioni ambientali (visibilità, illuminazione, umidità) ','Colore delle pareti'], correct:1 },
		{ q:'In caso di scarsa illuminazione o fumo, quale tipologia di segnaletica antincendio garantisce una maggiore efficacia?', a:['Cartelli opachi non riflettenti','Cartelli fotoluminescenti o retroilluminati ','Cartelli trasparenti'], correct:1 },
		{ q:'Qual è la distanza massima consigliata per il riconoscimento di un cartello antincendio di dimensioni standard (circa 20–30 cm di lato)?', a:['Circa 2–3 metri', 'Circa 10–12 metri ', 'Oltre 25 metri'], correct:1 },
		{ q:'In caso di percorso non lineare verso un estintore o un idrante, quale elemento grafico deve essere inserito sul cartello?', a:['Una scritta aggiuntiva','Una freccia di direzione appropriata ','Un bordo in colore giallo'], correct:1 },
		{ q:'Perché i cartelli antincendio non possono essere triangolari?', a:['Perché sarebbero troppo grandi','Perché la forma triangolare è riservata alla segnaletica di avvertimento, non a quella antincendio ','Perchè sono meno visibili'], correct:1  },
		{ q:'Se un cartello antincendio perde colore o contrasto nel tempo, quale azione è obbligatoria?', a:['Lasciarlo fino alla prossima ispezione programmata','Coprirlo temporaneamente','Sostituirlo immediatamente per mantenere la piena visibilità'], correct:2 },
		{ q:'In ambienti industriali con rischio di urti o vibrazioni, qual è la modalità più sicura di installazione dei cartelli antincendio?', a:['Posa temporanea con nastro adesivo','Fissaggio meccanico stabile (viti, supporti rigidi)','Montaggio magnetico leggero'], correct:1 },
		{ q:'Per quale motivo in alcuni luoghi si utilizzano cartelli antincendio di dimensioni maggiorate?', a:['Perchè si ha spazio a disposizione','Per incrementare la distanza di avvistamento in ambienti ampi o con ostacoli visivi', 'Per differenziarsi da altri reparti'], correct:1 },
		{ q:'Quale errore di collocazione rende inefficace un cartello antincendio?', a:['Installarlo vicino all’attrezzatura segnalata','Installarlo in un luogo sovrailluminato','Installarlo dietro ostacoli (armadi, porte aperte, scaffali) che ne impediscono la visibilità '], correct:2 },
      ],
    },
  };
